<a href="https://colab.research.google.com/github/surajkr214/Programming-For-Data-Science/blob/main/CN_5021_DS_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Sample Student ID
student_id_digits = [2,8,4,8,2,2,4]

# Question 1
print("--- Question 1 ---")

# Question 1a: Write code to create and show the array
print("\nQuestion 1a: Create and show the array")
arrayNumbers = np.array(student_id_digits)
print(arrayNumbers)

# Question 1b: Write code to display the size of the array
print("\nQuestion 1b: Display the size of the array")
print(arrayNumbers.size)

# Question 1c: Write code to show how you will retrieve the three middle elements of the array, using slicing.
print("\nQuestion 1c: Retrieve three middle elements using slicing")
# For an array with 7 elements, the middle three are at indices 2, 3, 4.
# Slicing goes from start_index to end_index (exclusive).
# So, arrayNumbers[2:5] will get elements at indices 2, 3, 4.
middle_elements = arrayNumbers[2:5]
print(middle_elements)

# Question 2
print("\n--- Question 2 ---")

# Question 2a: How you will create this array and display its values
print("\nQuestion 2a: Create and display the 2D array")
first_row = np.array(student_id_digits)
second_row = first_row * 2
third_row = first_row * 3

myNumbers = np.array([first_row, second_row, third_row])
print(myNumbers)

# Question 2b: How you will access and display the values in the second row, using indexing
print("\nQuestion 2b: Access and display values in the second row (indexing)")
# Rows are indexed starting from 0. The second row is at index 1.
second_row_values = myNumbers[1]
print(second_row_values)

# Question 2c: How you will access and display the first and second rows of values, using indexing
print("\nQuestion 2c: Access and display first and second rows (indexing)")
# To get the first and second rows, we can slice from row 0 up to (but not including) row 2.
first_and_second_rows = myNumbers[0:2]
print(first_and_second_rows)

# Question 2d: How you will access and display the second and third rows of values, using fancy indexing
print("\nQuestion 2d: Access and display second and third rows (fancy indexing)")
# Fancy indexing uses a list or array of indices.
second_and_third_rows_fancy = myNumbers[[1, 2]]
print(second_and_third_rows_fancy)

# Question 2e: How you will access and display all the rows of values, but only the last two columns
print("\nQuestion 2e: Access all rows, last two columns")
# To get all rows, use a colon :
# To get the last two columns, you can slice from -2 to the end :
all_rows_last_two_cols = myNumbers[:, -2:]
print(all_rows_last_two_cols)

# Question 2f: How you will display all the numbers in the array, which are greater than 10, using Boolean indexing
print("\nQuestion 2f: Display numbers greater than 10 (Boolean indexing)")
# Create a boolean array where elements are True if > 10, False otherwise
greater_than_10_mask = myNumbers > 10
# Use the boolean mask to select elements from myNumbers
numbers_greater_than_10 = myNumbers[greater_than_10_mask]
print(numbers_greater_than_10)

--- Question 1 ---

Question 1a: Create and show the array
[2 8 4 8 2 2 4]

Question 1b: Display the size of the array
7

Question 1c: Retrieve three middle elements using slicing
[4 8 2]

--- Question 2 ---

Question 2a: Create and display the 2D array
[[ 2  8  4  8  2  2  4]
 [ 4 16  8 16  4  4  8]
 [ 6 24 12 24  6  6 12]]

Question 2b: Access and display values in the second row (indexing)
[ 4 16  8 16  4  4  8]

Question 2c: Access and display first and second rows (indexing)
[[ 2  8  4  8  2  2  4]
 [ 4 16  8 16  4  4  8]]

Question 2d: Access and display second and third rows (fancy indexing)
[[ 4 16  8 16  4  4  8]
 [ 6 24 12 24  6  6 12]]

Question 2e: Access all rows, last two columns
[[ 2  4]
 [ 4  8]
 [ 6 12]]

Question 2f: Display numbers greater than 10 (Boolean indexing)
[16 16 24 12 24 12]
